// This is an automatically generated file, any changes will be overwritten on compiliation!


#ifndef EmbeddedFiles_AutoGenerated_H
#define EmbeddedFiles_AutoGenerated_H


#include "EmbeddedFiles_AutoGenerated_Blobs.h"
const char* const etag_file_logo_bmp = "\"d7fd7b25\"";
const size_t size_file_logo_bmp = 3834;

const char* const etag_file_logo_png = "\"1e133a5d\"";
const size_t size_file_logo_png = 8466;

#endif